### ISSUE TITLE
Update to work

### ISSUE THREAD

**Issue by ivanperez-keera** [joelburget/diagrams-opengl#1]
I know this is old but, any chance of getting this to work with a recent version of diagrams and GHC?

**Comment by joelburget** [comment]
Hi Ivan, unfortunately I don't think so. This isn't my primary interest these days so I don't want to commit to update and maintain this package.

**Comment by ivanperez-keera** [comment]
@joelburget Thanks.

I understand.

There's been several efforts to create gl backends for diagrams, all of which eventually become outdated. I would not mind maintaining one of them, but being unfamiliar with both diagrams and these implementations, I could really use some help putting the features from all of them together into one.

So far I have found:
https://github.com/mbernat/diagrams-opengl/
https://github.com/joelburget/diagrams-opengl/
https://github.com/cchalmers/diagrams-gl (only works for a fork of diagrams)
https://github.com/isomorphism/diagrams-gl

If we could, just as closure to this so that this effort can be carried on and people have a pointer to go on, somehow merge all existing efforts into one, I could take it from there.
